version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /buildtools/wasm
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
